filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/mylog.log
    fields:
      log_type: app
      service: myapp1
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/app/mylog.error.log
    fields:
      log_type: error
      service: myapp1
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
