server:
  port: 8080

spring:
  application:
    name: nebulazone

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nebulazone?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  token:
    access:
      second: 60
      minute: 60
      hour: 12
    refresh:
      second: 60
      minute: 60
      hour: 24

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
