name: CI

on:
  pull_request:
     branches:
       - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build -x test

#      - name: Run tests
#        run: ./gradlew clean test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=nebulazone
            -Dsonar.organization=nbc-7Guys
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.qualitygate.wait=true
