name: CI

on:
  pull_request:
     branches:
       - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew clean test
        env:
          SPRING_REDIS_HOST: localhost
          SPRING_REDIS_PORT: 6379
